[build]
  command = "npm run build"
  publish = "dist"
  
[template.environment]
  HUGO_VERSION = "0.29"

[context.deploy-preview]
  command = "npm run build-preview"
[build.environment]
  YARN_VERSION = "1.2.1"
  YARN_FLAGS = "--no-ignore-optional"